debug: false
management.endpoints.web,exposure.include: "*"

logging:
  level:
    com.fastcampus.projectboard: debug
    org.springframework.web.servlet: debug


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/board
    username: dmk
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100 # bulk select 를 위한 설정 (in)
  h2.console.enabled: true
  sql.init.mode: always

---

spring:
  config.activate.on-profile: test
  datasource:
    url: jdbc:h2:mem:board;mode=mysql
    driver-class-name: org.h2.Driver
  test.database.replace: none # 아직 문서화 X
